image: archlinux
oauth: pages.sr.ht/PAGES:RW
packages:
    - bun
    - hut
environment:
    site: lucaz.srht.site
sources:
    - https://git.sr.ht/~lucaz/seele
    - https://github.com/vollowx/seele-docs-skeleton
triggers:
    - action: email
      condition: failure
      to: "<vollowx@outlook.com>"
tasks:
    - setup: |
             cd seele
             bun install
    - build: |
             cd seele
             bun run build
    - setup-docs:  |
                   cd seele-docs-skeleton
                   bun add @vollowx/seele@file:../seele --save
                   cp -r ../seele/docs/ ./docs/
    - build-docs:  |
                   cd seele-docs-skeleton
                   bun run build
    - pack-docs:   |
                   cd seele-docs-skeleton
                   tar -C _site -cvz . > site.tar.gz
    - upload-docs: |
                   cd seele-docs-skeleton
                   hut pages publish -d $site site.tar.gz
submitter:
    git.sr.ht:
        enabled: true
        allow-refs:
            - refs/heads/main
            - "refs/tags/*"
